/*
 * Copyright 2025 Toni500git
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
 * products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include "state_manager.hpp"

#include <filesystem>
#include <string_view>
#include <utility>

#include "fmt/base.h"
#include "fmt/os.h"
#include "manifest.hpp"

StateManager::StateManager()
{
    if (!fs::exists(m_path))
    {
        auto f = fmt::output_file(m_path.string(), fmt::file::WRONLY | fmt::file::TRUNC | fmt::file::CREATE);
        f.print(R"(# AUTO-GENERATED FILE. DO NOT EDIT THIS FILE.
# YOU GONNA MESS SHIT UP. unless you know what you doing ofc
                )");
        f.close();
    }

    m_toml.LoadFile(m_path.string());
}

Result<> StateManager::AddNewRepo(const Manifest& manifest)
{
    const manifest_t& manrepo = manifest.GetRepo();

    toml::table& repositories = TomlAPI::EnsureTable(m_toml.GetTbl(), "repositories");
    toml::table& repo         = TomlAPI::EnsureTable(repositories, manrepo.name);
    repo.insert_or_assign("url", manrepo.url);
    repo.insert_or_assign("git-hash", manrepo.git_hash);

    toml::array plugins_arr;
    for (const plugin_t& plugin : manrepo.plugins)
    {
        // will be inserted in alphabetical order
        toml::table entry{ { "name", plugin.name },
                           { "id", plugin.id },
                           { "description", plugin.description },
                           { "authors", TomlAPI::VectorToArray(plugin.authors) },
                           { "licenses", TomlAPI::VectorToArray(plugin.licenses) } };

        plugins_arr.push_back(std::move(entry));
    }

    repo.insert_or_assign("plugins", std::move(plugins_arr));
    if (!SaveState())
        return Err("Failed to write plugin state of repository '{}'", manrepo.name);
    return Ok();
}

std::vector<manifest_t> StateManager::GetAllRepos() const
{
    const toml::table* repositories = m_toml.GetTbl()["repositories"].as_table();
    if (!repositories)
        return {};

    std::vector<manifest_t> manifests;
    for (const auto& [repo_name, repo_node] : *repositories)
    {
        const toml::table* repo_tbl = repo_node.as_table();
        if (!repo_tbl)
            continue;

        TomlAPI    repo_api(*repo_tbl);
        manifest_t manifest;
        manifest.name     = repo_name.str();
        manifest.url      = repo_api.GetValue<std::string>("url", "(unknown)");
        manifest.git_hash = repo_api.GetValue<std::string>("git-hash", "(unknown)");

        if (const toml::array* plugins = repo_tbl->get_as<toml::array>("plugins"))
        {
            for (const auto& plugin_node : *plugins)
            {
                const toml::table* plugin_tbl = plugin_node.as_table();
                if (!plugin_tbl)
                    continue;

                TomlAPI  plugin_api(*plugin_tbl);
                plugin_t plugin;
                plugin.name        = plugin_api.GetValue<std::string>("name", "(unknown)");
                plugin.id          = plugin_api.GetValue<std::string>("id", "(unknown)");
                plugin.description = plugin_api.GetValue<std::string>("description", "(unknown)");
                plugin.output_dir  = plugin_api.GetValue<std::string>("output-dir", "(unknown)");
                plugin.authors     = plugin_api.GetValueArrayStr("authors", {});
                plugin.licenses    = plugin_api.GetValueArrayStr("licenses", {});

                manifest.plugins.push_back(std::move(plugin));
            }
        }

        manifests.push_back(std::move(manifest));
    }

    return manifests;
}

Result<> StateManager::RemoveRepo(const std::string& repo)
{
    toml::table* repo_tbl = m_toml.GetTbl()["repositories"].as_table();
    if (!repo_tbl || !repo_tbl->contains(repo))
        return Err("Couldn't find repository '{}'", repo);

    repo_tbl->erase(repo);
    if (!SaveState())
        return Err("Failed to write plugin state of repository '{}'", repo);
    return Ok();
}
